config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get '/awaiting_confirmation',
    to: "users#confirmation",
    as: "confirm_user"

  root to: 'projects#index'

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
    to: 'admin/permissions#update',
    as: :update_user_permissions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>
  <% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    Ticketee
  <% end %>
</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
<% end %>

<nav>
  <ul class="navbar">
    <li><%= link_to "Home", root_path %></li>
    <% admins_only do %>
      <li><%= link_to "Admin", admin_root_path %></li>
    <% end %>

    <li class="login-info">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>